import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import Navbar from "@/components/Navbar/Navbar";
import NextTopLoader from "nextjs-toploader";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "IT Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <NextTopLoader
            color="#2299DD"
            initialPosition={0.08}
            height={4}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            showAtBottom={false}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
          />
          <Navbar />

          {children}
        </Provider>
      </body>
    </html>
  );
}
